import { COLORS } from '@/constants'
import { Styles } from '@/utils/styles'

export const styles: Styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: COLORS.background,
  },
  nav: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px',
    backgroundColor: COLORS.card,
    borderBottom: `1px solid ${COLORS.border}`,
  },
  back: {
    fontSize: '24px',
    color: COLORS.text,
    cursor: 'pointer',
  },
  navTitle: {
    fontSize: '17px',
    fontWeight: 'bold',
    color: COLORS.text,
  },
  centerContent: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '60px 24px 24px',
  },
  iconLarge: {
    fontSize: '72px',
    marginBottom: '20px',
  },
  title: {
    fontSize: '22px',
    fontWeight: 'bold',
    color: COLORS.text,
    margin: '0 0 12px 0',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: '14px',
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: 1.6,
    margin: '0 0 20px 0',
  },
  time: {
    fontSize: '12px',
    color: COLORS.textSecondary,
    marginBottom: '32px',
  },
  steps: {
    width: '100%',
    maxWidth: '280px',
    marginBottom: '40px',
  },
  step: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '16px',
    position: 'relative',
  },
  stepDot: {
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    color: '#fff',
    flexShrink: 0,
  },
  stepLine: {
    position: 'absolute',
    left: '11px',
    top: '-16px',
    width: '2px',
    height: '16px',
  },
  stepText: {
    fontSize: '14px',
    marginLeft: '8px',
  },
  primaryBtn: {
    width: '100%',
    maxWidth: '280px',
    padding: '14px',
    background: `linear-gradient(135deg, ${COLORS.primary} 0%, ${COLORS.secondary} 100%)`,
    border: 'none',
    borderRadius: '25px',
    fontSize: '15px',
    fontWeight: 'bold',
    color: '#fff',
    cursor: 'pointer',
    marginBottom: '12px',
  },
  ghostBtn: {
    width: '100%',
    maxWidth: '280px',
    padding: '14px',
    backgroundColor: 'transparent',
    border: `1px solid ${COLORS.border}`,
    borderRadius: '25px',
    fontSize: '15px',
    color: COLORS.textSecondary,
    cursor: 'pointer',
  },
  spinnerWrap: {
    marginBottom: '20px',
  },
  spinner: {
    width: '56px',
    height: '56px',
    border: `4px solid ${COLORS.border}`,
    borderTopColor: COLORS.primary,
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
}
