import { COLORS } from '@/constants'
import { Styles } from '@/utils/styles'

export const styles: Styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: COLORS.background,
    color: COLORS.text,
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    backgroundColor: COLORS.card,
    padding: '16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: `1px solid ${COLORS.border}`,
  },
  headerTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: COLORS.text,
  },
  headerRight: {
    fontSize: '20px',
    cursor: 'pointer',
  },
  tabBar: {
    display: 'flex',
    padding: '12px 20px',
    gap: '24px',
    backgroundColor: COLORS.card,
    borderBottom: `1px solid ${COLORS.border}`,
  },
  tab: {
    fontSize: '15px',
    color: COLORS.textSecondary,
    paddingBottom: '8px',
    cursor: 'pointer',
    borderBottom: '2px solid transparent',
    position: 'relative',
  },
  tabIndicator: {
    position: 'absolute',
    bottom: '-1px',
    left: 0,
    right: 0,
    height: '2px',
    backgroundColor: COLORS.primary,
    borderRadius: '1px',
  },
  tabActive: {
    color: COLORS.primary,
    borderBottomColor: COLORS.primary,
    fontWeight: 'bold',
  },
  chatList: {
    flex: 1,
    overflow: 'auto',
  },
  chatItem: {
    display: 'flex',
    alignItems: 'center',
    padding: '14px 16px',
    borderBottom: `1px solid ${COLORS.border}`,
    cursor: 'pointer',
    backgroundColor: COLORS.card,
  },
  avatarWrapper: {
    position: 'relative',
    marginRight: '12px',
  },
  avatar: {
    fontSize: '48px',
    display: 'block',
  },
  onlineDot: {
    position: 'absolute',
    bottom: '2px',
    right: '2px',
    width: '12px',
    height: '12px',
    backgroundColor: COLORS.success,
    borderRadius: '50%',
    border: `2px solid ${COLORS.card}`,
  },
  chatContent: {
    flex: 1,
  },
  chatTop: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '4px',
  },
  chatName: {
    fontSize: '15px',
    fontWeight: 'bold',
    color: COLORS.text,
  },
  chatTime: {
    fontSize: '11px',
    color: COLORS.textSecondary,
  },
  chatBottom: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  lastMsg: {
    fontSize: '13px',
    color: COLORS.textSecondary,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: '200px',
  },
  unreadBadge: {
    backgroundColor: COLORS.primary,
    color: '#fff',
    fontSize: '11px',
    padding: '2px 6px',
    borderRadius: '10px',
    minWidth: '18px',
    textAlign: 'center',
  },
  chatHeader: {
    backgroundColor: COLORS.card,
    padding: '12px 16px',
    display: 'flex',
    alignItems: 'center',
    borderBottom: `1px solid ${COLORS.border}`,
  },
  backBtn: {
    fontSize: '24px',
    cursor: 'pointer',
    marginRight: '12px',
    color: COLORS.text,
  },
  chatHeaderInfo: {
    flex: 1,
  },
  chatHeaderName: {
    fontSize: '16px',
    fontWeight: 'bold',
    display: 'block',
    color: COLORS.text,
  },
  chatHeaderStatus: {
    fontSize: '11px',
    color: COLORS.textSecondary,
  },
  moreBtn: {
    fontSize: '20px',
    cursor: 'pointer',
    color: COLORS.text,
  },
  messageList: {
    flex: 1,
    padding: '16px',
    overflow: 'auto',
    backgroundColor: COLORS.background,
  },
  systemMsg: {
    textAlign: 'center',
    fontSize: '12px',
    color: COLORS.textSecondary,
    margin: '10px 0',
  },
  selfMsgWrapper: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    marginBottom: '12px',
    gap: '6px',
  },
  selfBubble: {
    backgroundColor: COLORS.primary,
    color: '#fff',
    padding: '10px 14px',
    borderRadius: '18px 4px 18px 18px',
    maxWidth: '70%',
    fontSize: '14px',
    lineHeight: '1.4',
  },
  otherMsgWrapper: {
    display: 'flex',
    alignItems: 'flex-start',
    marginBottom: '12px',
    gap: '8px',
  },
  otherAvatar: {
    fontSize: '36px',
    display: 'block',
  },
  otherName: {
    fontSize: '11px',
    color: COLORS.textSecondary,
    marginBottom: '2px',
    display: 'block',
  },
  otherBubble: {
    backgroundColor: COLORS.card,
    color: COLORS.text,
    padding: '10px 14px',
    borderRadius: '4px 18px 18px 18px',
    maxWidth: '70%',
    fontSize: '14px',
    lineHeight: '1.4',
    border: `1px solid ${COLORS.border}`,
  },
  msgTime: {
    fontSize: '10px',
    color: COLORS.textSecondary,
    alignSelf: 'flex-end',
  },
  inputBar: {
    backgroundColor: COLORS.card,
    padding: '10px 16px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    borderTop: `1px solid ${COLORS.border}`,
  },
  inputIcon: {
    fontSize: '22px',
    cursor: 'pointer',
    color: COLORS.textSecondary,
  },
  input: {
    flex: 1,
    backgroundColor: COLORS.background,
    border: `1px solid ${COLORS.border}`,
    borderRadius: '20px',
    padding: '10px 16px',
    color: COLORS.text,
    fontSize: '14px',
    outline: 'none',
  },
  sendBtn: {
    background: `linear-gradient(135deg, ${COLORS.primary} 0%, ${COLORS.secondary} 100%)`,
    color: '#fff',
    padding: '8px 16px',
    borderRadius: '16px',
    fontSize: '13px',
    fontWeight: 'bold',
    boxShadow: `0 4px 12px ${COLORS.primary}40`,
    border: 'none',
    cursor: 'pointer',
  },
}

