import { COLORS } from "@/constants"
import { Styles } from "@/utils/styles"

export const styles: Styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: COLORS.background,
    paddingBottom: '80px',
  },
  header: {
    backgroundColor: COLORS.card,
    padding: '14px 16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backBtn: {
    fontSize: '24px',
    cursor: 'pointer',
    color: COLORS.text,
  },
  headerTitle: {
    fontSize: '17px',
    fontWeight: 'bold',
    color: COLORS.text,
  },
  moreBtn: {
    fontSize: '20px',
    cursor: 'pointer',
    color: COLORS.text,
  },
  statusCard: {
    background: `linear-gradient(135deg, ${COLORS.primary} 0%, #c44569 100%)`,
    margin: '16px',
    borderRadius: '16px',
    padding: '20px',
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  statusIcon: {
    fontSize: '40px',
  },
  statusInfo: {
    flex: 1,
  },
  statusText: {
    display: 'block',
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: '4px',
  },
  statusDesc: {
    fontSize: '13px',
    color: 'rgba(255,255,255,0.8)',
  },
  section: {
    padding: '16px',
    borderBottom: `1px solid ${COLORS.border}`,
  },
  sectionTitle: {
    fontSize: '15px',
    fontWeight: 'bold',
    color: COLORS.text,
    margin: '0 0 14px 0',
  },
  boosterCard: {
    backgroundColor: COLORS.card,
    borderRadius: '12px',
    padding: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    border: `1px solid ${COLORS.border}`,
  },
  boosterAvatar: {
    fontSize: '48px',
  },
  boosterInfo: {
    flex: 1,
  },
  boosterName: {
    display: 'block',
    fontSize: '17px',
    fontWeight: 'bold',
    color: COLORS.text,
    marginBottom: '4px',
  },
  boosterLevel: {
    display: 'block',
    fontSize: '12px',
    color: '#FFD700',
    marginBottom: '2px',
  },
  boosterRating: {
    fontSize: '13px',
    color: '#FFD700',
  },
  boosterActions: {
    display: 'flex',
    gap: '10px',
  },
  chatBtn: {
    width: '44px',
    height: '44px',
    borderRadius: '50%',
    backgroundColor: 'rgba(255,107,157,0.2)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    cursor: 'pointer',
  },
  callBtn: {
    width: '44px',
    height: '44px',
    borderRadius: '50%',
    backgroundColor: 'rgba(76,175,80,0.2)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    cursor: 'pointer',
  },
  infoGrid: {
    backgroundColor: COLORS.card,
    borderRadius: '12px',
    padding: '4px 0',
    border: `1px solid ${COLORS.border}`,
  },
  infoRow: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '12px 16px',
    borderBottom: `1px solid ${COLORS.border}`,
  },
  infoLabel: {
    fontSize: '14px',
    color: COLORS.textSecondary,
  },
  infoValue: {
    fontSize: '14px',
    color: COLORS.text,
  },
  priceCard: {
    backgroundColor: COLORS.card,
    borderRadius: '12px',
    padding: '16px',
    border: `1px solid ${COLORS.border}`,
  },
  priceRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '12px',
  },
  priceLabel: {
    fontSize: '14px',
    color: COLORS.textSecondary,
  },
  priceText: {
    fontSize: '14px',
    color: COLORS.textSecondary,
  },
  priceDivider: {
    height: '1px',
    backgroundColor: COLORS.border,
    margin: '12px 0',
  },
  totalLabel: {
    fontSize: '15px',
    fontWeight: 'bold',
    color: COLORS.text,
  },
  totalValue: {
    fontSize: '22px',
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  bottomBar: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    maxWidth: '480px',
    margin: '0 auto',
    backgroundColor: COLORS.card,
    padding: '12px 16px',
    display: 'flex',
    gap: '12px',
    borderTop: `1px solid ${COLORS.border}`,
    zIndex: 100,
  },
  cancelBtn: {
    flex: 1,
    padding: '14px',
    borderRadius: '24px',
    border: `1px solid ${COLORS.border}`,
    color: COLORS.textSecondary,
    textAlign: 'center',
    fontSize: '15px',
    cursor: 'pointer',
  },
  editBtn: {
    flex: 1,
    padding: '14px',
    borderRadius: '24px',
    backgroundColor: 'rgba(255,255,255,0.1)',
    color: COLORS.text,
    textAlign: 'center',
    fontSize: '15px',
    cursor: 'pointer',
  },
  chatMainBtn: {
    flex: 1,
    padding: '14px',
    borderRadius: '24px',
    background: `linear-gradient(135deg, ${COLORS.primary} 0%, ${COLORS.secondary} 100%)`,
    color: '#fff',
    textAlign: 'center',
    fontSize: '15px',
    fontWeight: 'bold',
    cursor: 'pointer',
    boxShadow: `0 4px 15px ${COLORS.primary}40`,
    border: 'none',
  },
  reOrderBtn: {
    flex: 1,
    padding: '14px',
    borderRadius: '24px',
    backgroundColor: COLORS.primary,
    color: '#fff',
    textAlign: 'center',
    fontSize: '15px',
    fontWeight: 'bold',
    cursor: 'pointer',
    border: 'none',
  },
  rateBtn: {
    flex: 1,
    padding: '14px',
    borderRadius: '24px',
    background: `linear-gradient(135deg, ${COLORS.warning} 0%, #ff9500 100%)`,
    color: '#fff',
    textAlign: 'center',
    fontSize: '15px',
    fontWeight: 'bold',
    cursor: 'pointer',
    border: 'none',
    boxShadow: `0 4px 15px ${COLORS.warning}40`,
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 200,
  },
  modal: {
    backgroundColor: COLORS.card,
    borderRadius: '16px',
    padding: '24px',
    margin: '20px',
    maxWidth: '300px',
    width: '100%',
    border: `1px solid ${COLORS.border}`,
  },
  modalTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: COLORS.text,
    textAlign: 'center',
    margin: '0 0 10px 0',
  },
  modalDesc: {
    fontSize: '14px',
    color: COLORS.textSecondary,
    textAlign: 'center',
    margin: '0 0 20px 0',
  },
  modalBtns: {
    display: 'flex',
    gap: '12px',
  },
  modalCancel: {
    flex: 1,
    padding: '12px',
    borderRadius: '20px',
    border: `1px solid ${COLORS.border}`,
    color: COLORS.textSecondary,
    textAlign: 'center',
    fontSize: '14px',
    cursor: 'pointer',
  },
  modalConfirm: {
    flex: 1,
    padding: '12px',
    borderRadius: '20px',
    backgroundColor: COLORS.primary,
    color: '#fff',
    textAlign: 'center',
    fontSize: '14px',
    fontWeight: 'bold',
    cursor: 'pointer',
    border: 'none',
  },
}

