import { COLORS } from "@/constants"
import { Styles } from "@/utils/styles"

export const styles: Styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: COLORS.background,
  },
  header: {
    backgroundColor: COLORS.card,
    padding: '14px 16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backBtn: {
    fontSize: '24px',
    cursor: 'pointer',
    color: COLORS.text,
  },
  headerTitle: {
    fontSize: '17px',
    fontWeight: 'bold',
    color: COLORS.text,
  },
  placeholder: {
    width: '24px',
  },
  countdownBar: {
    backgroundColor: 'rgba(255,107,157,0.15)',
    padding: '12px 16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  countdownLabel: {
    fontSize: '13px',
    color: COLORS.primary,
  },
  countdownTime: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: COLORS.primary,
    fontFamily: 'monospace',
  },
  orderSummary: {
    backgroundColor: COLORS.card,
    margin: '16px',
    borderRadius: '12px',
    padding: '4px 0',
    border: `1px solid ${COLORS.border}`,
  },
  summaryRow: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '12px 16px',
  },
  summaryLabel: {
    fontSize: '14px',
    color: COLORS.textSecondary,
  },
  summaryValue: {
    fontSize: '14px',
    color: COLORS.text,
  },
  section: {
    padding: '16px',
  },
  sectionTitle: {
    fontSize: '15px',
    fontWeight: 'bold',
    color: COLORS.text,
    margin: '0 0 14px 0',
  },
  methodItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.card,
    borderRadius: '12px',
    padding: '16px',
    marginBottom: '10px',
    cursor: 'pointer',
    border: `2px solid transparent`,
  },
  methodActive: {
    borderColor: COLORS.primary,
    backgroundColor: 'rgba(255,107,157,0.1)',
  },
  methodLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  methodIcon: {
    fontSize: '24px',
  },
  methodName: {
    fontSize: '15px',
    color: COLORS.text,
  },
  methodRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  recommendTag: {
    backgroundColor: COLORS.primary,
    color: '#fff',
    fontSize: '10px',
    padding: '2px 6px',
    borderRadius: '4px',
  },
  radio: {
    width: '22px',
    height: '22px',
    borderRadius: '50%',
    border: `2px solid ${COLORS.border}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioActive: {
    borderColor: COLORS.primary,
  },
  radioInner: {
    width: '12px',
    height: '12px',
    borderRadius: '50%',
    backgroundColor: COLORS.primary,
  },
  amountSection: {
    padding: '20px 16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTop: `1px solid ${COLORS.border}`,
    marginTop: '10px',
  },
  amountLabel: {
    fontSize: '15px',
    color: COLORS.textSecondary,
  },
  amountValue: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  bottomBar: {
    padding: '16px',
  },
  payBtn: {
    width: '100%',
    padding: '16px',
    background: `linear-gradient(135deg, ${COLORS.primary} 0%, ${COLORS.secondary} 100%)`,
    color: '#fff',
    border: 'none',
    borderRadius: '25px',
    fontSize: '17px',
    fontWeight: 'bold',
    cursor: 'pointer',
    boxShadow: `0 4px 15px ${COLORS.primary}40`,
  },
  payBtnDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  securityTip: {
    textAlign: 'center',
    fontSize: '11px',
    color: COLORS.textSecondary,
    padding: '0 20px 20px',
    margin: 0,
  },
  // 浮层
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    zIndex: 200,
  },
  bottomSheet: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    maxWidth: '480px',
    margin: '0 auto',
    backgroundColor: COLORS.card,
    borderRadius: '20px 20px 0 0',
    padding: '0 0 32px 0',
    zIndex: 201,
    maxHeight: '80vh',
    overflowY: 'auto',
  },
  sheetHandle: {
    width: '40px',
    height: '4px',
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: '2px',
    margin: '12px auto 0',
  },
  sheetHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 20px',
    borderBottom: `1px solid ${COLORS.border}`,
  },
  sheetTitle: {
    fontSize: '17px',
    fontWeight: 'bold',
    color: COLORS.text,
    margin: 0,
  },
  sheetClose: {
    fontSize: '18px',
    color: COLORS.textSecondary,
    cursor: 'pointer',
    padding: '4px',
  },
  rulesList: {
    padding: '16px 20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  ruleItem: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: '12px',
    padding: '14px',
    border: `1px solid ${COLORS.border}`,
  },
  ruleTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '8px',
  },
  ruleIcon: {
    fontSize: '16px',
  },
  ruleTitle: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: COLORS.text,
  },
  ruleContent: {
    fontSize: '13px',
    color: COLORS.textSecondary,
    lineHeight: '1.6',
    margin: 0,
  },
  agreeRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '0 20px 16px',
    cursor: 'pointer',
  },
  checkbox: {
    width: '22px',
    height: '22px',
    borderRadius: '6px',
    border: `2px solid ${COLORS.border}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  checkboxChecked: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  checkmark: {
    color: '#fff',
    fontSize: '14px',
    fontWeight: 'bold',
  },
  agreeText: {
    fontSize: '14px',
    color: COLORS.text,
  },
  confirmBtn: {
    display: 'block',
    width: 'calc(100% - 40px)',
    margin: '0 20px',
    padding: '16px',
    background: `linear-gradient(135deg, ${COLORS.primary} 0%, ${COLORS.secondary} 100%)`,
    color: '#fff',
    border: 'none',
    borderRadius: '25px',
    fontSize: '16px',
    fontWeight: 'bold',
    cursor: 'pointer',
    boxShadow: `0 4px 15px ${COLORS.primary}40`,
  },
  confirmBtnDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
  },
}
