import { COLORS } from '@/constants'
import { Styles } from '@/utils/styles'

export const styles: Styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: COLORS.background,
    paddingBottom: '40px',
  },
  nav: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px',
    backgroundColor: COLORS.card,
    borderBottom: `1px solid ${COLORS.border}`,
  },
  back: {
    fontSize: '24px',
    color: COLORS.text,
    cursor: 'pointer',
  },
  navTitle: {
    fontSize: '17px',
    fontWeight: 'bold',
    color: COLORS.text,
  },
  editBtn: {
    fontSize: '15px',
    color: COLORS.primary,
    cursor: 'pointer',
  },
  headerSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    padding: '20px 16px',
    backgroundColor: COLORS.card,
    marginBottom: '12px',
  },
  avatar: {
    width: '72px',
    height: '72px',
    borderRadius: '50%',
    objectFit: 'cover',
    border: `3px solid ${COLORS.primary}`,
  },
  headerInfo: {
    flex: 1,
  },
  name: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: COLORS.text,
    margin: '0 0 6px 0',
  },
  subInfo: {
    fontSize: '13px',
    color: COLORS.textSecondary,
    margin: '0 0 6px 0',
  },
  onlineIndicator: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    color: COLORS.success,
    margin: 0,
  },
  onlineDot: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    backgroundColor: COLORS.success,
  },
  statsCard: {
    display: 'flex',
    backgroundColor: COLORS.card,
    margin: '0 12px 12px',
    borderRadius: '12px',
    padding: '16px',
    border: `1px solid ${COLORS.border}`,
  },
  statItem: {
    flex: 1,
    textAlign: 'center',
  },
  statValue: {
    display: 'block',
    fontSize: '18px',
    fontWeight: 'bold',
    color: COLORS.text,
  },
  statLabel: {
    fontSize: '11px',
    color: COLORS.textSecondary,
  },
  statDivider: {
    width: '1px',
    backgroundColor: COLORS.border,
    margin: '0 8px',
  },
  editSection: {
    padding: '0 12px',
  },
  readonlySection: {
    padding: '0 12px',
  },
  field: {
    marginBottom: '20px',
  },
  fieldLabel: {
    fontSize: '13px',
    color: COLORS.textSecondary,
    marginBottom: '8px',
    fontWeight: 'bold',
  },
  priceRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  slider: {
    flex: 1,
    accentColor: COLORS.primary,
  },
  priceTag: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: COLORS.primary,
    minWidth: '60px',
    textAlign: 'right',
  },
  chipGroup: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  chip: {
    padding: '6px 14px',
    borderRadius: '16px',
    border: '1px solid',
    fontSize: '13px',
    color: COLORS.text,
    cursor: 'pointer',
  },
  textarea: {
    width: '100%',
    backgroundColor: COLORS.card,
    border: `1px solid ${COLORS.border}`,
    borderRadius: '12px',
    padding: '12px',
    fontSize: '14px',
    color: COLORS.text,
    resize: 'none',
    outline: 'none',
    boxSizing: 'border-box',
  },
  description: {
    fontSize: '14px',
    color: COLORS.text,
    lineHeight: 1.6,
    margin: 0,
    backgroundColor: COLORS.card,
    padding: '12px',
    borderRadius: '12px',
    border: `1px solid ${COLORS.border}`,
  },
  editActions: {
    display: 'flex',
    gap: '12px',
    marginTop: '8px',
  },
  cancelBtn: {
    flex: 1,
    padding: '14px',
    backgroundColor: 'transparent',
    border: `1px solid ${COLORS.border}`,
    borderRadius: '25px',
    fontSize: '15px',
    color: COLORS.textSecondary,
    cursor: 'pointer',
  },
  saveBtn: {
    flex: 2,
    padding: '14px',
    background: `linear-gradient(135deg, ${COLORS.primary} 0%, ${COLORS.secondary} 100%)`,
    border: 'none',
    borderRadius: '25px',
    fontSize: '15px',
    fontWeight: 'bold',
    color: '#fff',
    cursor: 'pointer',
  },
}
