import { COLORS } from '@/constants'
import { Styles } from '@/utils/styles'

export const styles: Styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: COLORS.background,
    paddingBottom: '80px',
  },
  nav: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px',
    backgroundColor: COLORS.card,
    borderBottom: `1px solid ${COLORS.border}`,
  },
  navTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: COLORS.text,
  },
  onlineTag: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '13px',
    color: COLORS.success,
    backgroundColor: 'rgba(0,217,166,0.15)',
    padding: '4px 10px',
    borderRadius: '12px',
  },
  onlineDot: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    backgroundColor: COLORS.success,
  },
  overviewCard: {
    backgroundColor: COLORS.card,
    margin: '12px',
    borderRadius: '16px',
    padding: '16px',
    border: `1px solid ${COLORS.border}`,
  },
  profileRow: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '16px',
  },
  avatar: {
    width: '52px',
    height: '52px',
    borderRadius: '50%',
    backgroundColor: COLORS.border,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    fontSize: '28px',
    marginRight: '12px',
  },
  avatarImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: '17px',
    fontWeight: 'bold',
    color: COLORS.text,
    margin: '0 0 4px 0',
  },
  profileGames: {
    fontSize: '12px',
    color: COLORS.textSecondary,
    margin: 0,
  },
  editBtn: {
    padding: '6px 14px',
    backgroundColor: 'transparent',
    border: `1px solid ${COLORS.primary}`,
    borderRadius: '16px',
    fontSize: '12px',
    color: COLORS.primary,
    cursor: 'pointer',
  },
  statsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingTop: '12px',
    borderTop: `1px solid ${COLORS.border}`,
  },
  statItem: {
    textAlign: 'center',
    flex: 1,
  },
  statValue: {
    display: 'block',
    fontSize: '20px',
    fontWeight: 'bold',
    color: COLORS.text,
  },
  statLabel: {
    fontSize: '11px',
    color: COLORS.textSecondary,
  },
  statDivider: {
    width: '1px',
    height: '30px',
    backgroundColor: COLORS.border,
  },
  balanceCard: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.card,
    margin: '0 12px 12px',
    borderRadius: '16px',
    padding: '16px',
    border: `1px solid ${COLORS.border}`,
    cursor: 'pointer',
  },
  balanceLabel: {
    fontSize: '12px',
    color: COLORS.textSecondary,
    margin: '0 0 4px 0',
  },
  balanceValue: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: COLORS.primary,
    margin: 0,
  },
  withdrawInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  pendingWithdraw: {
    fontSize: '12px',
    color: COLORS.textSecondary,
  },
  arrow: {
    fontSize: '16px',
    color: COLORS.textSecondary,
  },
  section: {
    margin: '0 12px 12px',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '10px',
    gap: '8px',
  },
  sectionTitle: {
    fontSize: '15px',
    fontWeight: 'bold',
    color: COLORS.text,
  },
  badge: {
    backgroundColor: COLORS.error,
    color: '#fff',
    fontSize: '11px',
    padding: '2px 8px',
    borderRadius: '10px',
  },
  badgeInProgress: {
    backgroundColor: COLORS.success,
    color: '#fff',
    fontSize: '11px',
    padding: '2px 8px',
    borderRadius: '10px',
  },
  moreLink: {
    marginLeft: 'auto',
    fontSize: '13px',
    color: COLORS.textSecondary,
    cursor: 'pointer',
  },
  emptyCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '24px',
    backgroundColor: COLORS.card,
    borderRadius: '12px',
    border: `1px solid ${COLORS.border}`,
  },
  emptyIcon: {
    fontSize: '32px',
    marginBottom: '8px',
  },
  emptyText: {
    fontSize: '13px',
    color: COLORS.textSecondary,
  },
  orderCard: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.card,
    borderRadius: '12px',
    padding: '12px',
    marginBottom: '8px',
    border: `1px solid ${COLORS.border}`,
  },
  orderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  orderAvatar: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    objectFit: 'cover',
  },
  orderName: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: COLORS.text,
    margin: '0 0 4px 0',
  },
  orderMeta: {
    fontSize: '12px',
    color: COLORS.textSecondary,
    margin: 0,
  },
  orderActions: {
    display: 'flex',
    gap: '8px',
  },
  acceptBtn: {
    padding: '6px 16px',
    backgroundColor: COLORS.success,
    border: 'none',
    borderRadius: '14px',
    fontSize: '12px',
    color: '#fff',
    cursor: 'pointer',
  },
  rejectBtn: {
    padding: '6px 16px',
    backgroundColor: 'transparent',
    border: `1px solid ${COLORS.error}`,
    borderRadius: '14px',
    fontSize: '12px',
    color: COLORS.error,
    cursor: 'pointer',
  },
  inProgressTag: {
    padding: '4px 10px',
    backgroundColor: 'rgba(0,217,166,0.15)',
    color: COLORS.success,
    borderRadius: '10px',
    fontSize: '12px',
  },
  menuGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '1px',
    margin: '16px 12px 0',
    backgroundColor: COLORS.border,
    borderRadius: '12px',
    overflow: 'hidden',
  },
  menuItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '16px 8px',
    backgroundColor: COLORS.card,
    cursor: 'pointer',
  },
  menuIcon: {
    fontSize: '24px',
    marginBottom: '6px',
  },
  menuLabel: {
    fontSize: '12px',
    color: COLORS.text,
  },
}
