import { COLORS } from '@/constants'
import { Styles } from '@/utils/styles'

export const styles: Styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: COLORS.background,
    paddingBottom: '80px',
  },
  header: {
    backgroundColor: COLORS.card,
    padding: '14px 16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
  backBtn: {
    fontSize: '24px',
    cursor: 'pointer',
    color: COLORS.text,
  },
  headerTitle: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: COLORS.text,
  },
  shareBtn: {
    fontSize: '14px',
    color: COLORS.primary,
    cursor: 'pointer',
  },
  profileSection: {
    background: `linear-gradient(135deg, ${COLORS.primary} 0%, #c44569 100%)`,
    padding: '20px 16px',
    display: 'flex',
    gap: '16px',
    alignItems: 'flex-start',
  },
  avatarWrapper: {
    position: 'relative',
    flexShrink: 0,
  },
  avatarImg: {
    width: '72px',
    height: '72px',
    borderRadius: '50%',
    objectFit: 'cover',
  },
  avatarEmoji: {
    fontSize: '72px',
    display: 'block',
  },
  onlineBadge: {
    position: 'absolute',
    bottom: '4px',
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: COLORS.success,
    color: '#fff',
    fontSize: '10px',
    padding: '2px 8px',
    borderRadius: '10px',
    whiteSpace: 'nowrap',
  },
  profileInfo: {
    flex: 1,
    color: '#fff',
  },
  nameRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '8px',
  },
  name: {
    fontSize: '22px',
    fontWeight: 'bold',
    color: '#fff',
  },
  level: {
    fontSize: '12px',
    fontWeight: 'bold',
    padding: '2px 8px',
    borderRadius: '8px',
  },
  gameInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '10px',
  },
  gameTag: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    padding: '3px 10px',
    borderRadius: '10px',
    fontSize: '12px',
    color: '#fff',
  },
  rank: {
    fontSize: '13px',
    color: 'rgba(255,255,255,0.8)',
  },
  statsRow: {
    display: 'flex',
    gap: '16px',
    fontSize: '13px',
    color: '#fff',
  },
  priceTag: {
    color: '#FFD700',
    fontWeight: 'bold',
  },
  tabBar: {
    display: 'flex',
    backgroundColor: COLORS.card,
    borderBottom: `1px solid ${COLORS.border}`,
  },
  tab: {
    flex: 1,
    textAlign: 'center',
    padding: '14px 0',
    fontSize: '15px',
    color: COLORS.textSecondary,
    cursor: 'pointer',
    position: 'relative',
  },
  tabActive: {
    color: COLORS.primary,
    fontWeight: 'bold',
  },
  tabIndicator: {
    position: 'absolute',
    bottom: 0,
    left: '25%',
    right: '25%',
    height: 2,
    borderRadius: 1,
    backgroundColor: COLORS.primary,
  },
  section: {
    padding: '16px',
    borderBottom: `1px solid ${COLORS.border}`,
  },
  sectionTitle: {
    fontSize: '15px',
    fontWeight: 'bold',
    color: COLORS.text,
    margin: '0 0 12px 0',
  },
  gameOptions: {
    display: 'flex',
    gap: '10px',
    flexWrap: 'wrap',
  },
  gameOption: {
    padding: '8px 16px',
    borderRadius: '20px',
    fontSize: '13px',
    color: COLORS.textSecondary,
    backgroundColor: 'rgba(255,255,255,0.08)',
    cursor: 'pointer',
    border: '1px solid transparent',
  },
  gameOptionActive: {
    backgroundColor: COLORS.primary,
    color: '#fff',
    fontWeight: 'bold',
  },
  hoursOptions: {
    display: 'flex',
    gap: '10px',
    marginBottom: '16px',
  },
  hourOption: {
    flex: 1,
    padding: '12px 8px',
    borderRadius: '12px',
    backgroundColor: 'rgba(255,255,255,0.08)',
    textAlign: 'center',
    cursor: 'pointer',
    border: '2px solid transparent',
  },
  hourOptionActive: {
    borderColor: COLORS.primary,
    backgroundColor: 'rgba(255,107,157,0.15)',
  },
  hourValue: {
    display: 'block',
    fontSize: '20px',
    fontWeight: 'bold',
    color: COLORS.text,
  },
  hourLabel: {
    fontSize: '11px',
    color: COLORS.textSecondary,
  },
  priceSummary: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    padding: '12px 16px',
    borderRadius: '12px',
  },
  priceSummaryLabel: {
    color: COLORS.textSecondary,
    fontSize: '14px',
  },
  totalPrice: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  tags: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
  },
  tag: {
    padding: '6px 12px',
    borderRadius: '16px',
    fontSize: '13px',
    color: COLORS.text,
    backgroundColor: 'rgba(255,107,157,0.15)',
    border: `1px solid ${COLORS.primary}40`,
  },
  bio: {
    fontSize: '14px',
    color: COLORS.textSecondary,
    lineHeight: '1.6',
    margin: 0,
  },
  similarScroll: {
    display: 'flex',
    gap: '12px',
    overflowX: 'auto',
    paddingBottom: '4px',
  },
  similarCard: {
    flexShrink: 0,
    width: '90px',
    backgroundColor: COLORS.card,
    borderRadius: '12px',
    padding: '12px 8px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    cursor: 'pointer',
    border: `1px solid ${COLORS.border}`,
  },
  similarAvatar: {
    position: 'relative',
    width: '48px',
    height: '48px',
    borderRadius: '50%',
    backgroundColor: 'rgba(255,255,255,0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: '4px',
  },
  similarAvatarImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  similarAvatarEmoji: {
    fontSize: '24px',
  },
  similarOnlineDot: {
    position: 'absolute',
    bottom: '2px',
    right: '2px',
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    backgroundColor: COLORS.success,
    border: '2px solid rgba(26,26,46,1)',
  },
  similarName: {
    fontSize: '12px',
    fontWeight: 'bold',
    color: COLORS.text,
    textAlign: 'center',
  },
  similarPrice: {
    fontSize: '11px',
    color: '#FFD700',
    fontWeight: 'bold',
  },
  similarRating: {
    fontSize: '10px',
    color: COLORS.textSecondary,
  },
  reviewsSection: {
    padding: '16px',
  },
  reviewsLoading: {
    display: 'flex',
    justifyContent: 'center',
    padding: '40px 0',
  },
  reviewsEmpty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    paddingTop: '40px',
    gap: '8px',
  },
  emptyIcon: {
    fontSize: '40px',
  },
  emptyText: {
    fontSize: '15px',
    color: COLORS.text,
  },
  emptySub: {
    fontSize: '13px',
    color: COLORS.textSecondary,
  },
  reviewItem: {
    backgroundColor: COLORS.card,
    borderRadius: '12px',
    padding: '14px',
    marginBottom: '10px',
    border: `1px solid ${COLORS.border}`,
  },
  reviewHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '10px',
  },
  reviewerAvatar: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    backgroundColor: 'rgba(255,255,255,0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    fontSize: '20px',
    flexShrink: 0,
  },
  reviewerAvatarImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  reviewerInfo: {
    flex: 1,
  },
  reviewerName: {
    display: 'block',
    fontSize: '14px',
    fontWeight: 'bold',
    color: COLORS.text,
  },
  reviewRating: {
    fontSize: '12px',
    color: '#FFD700',
  },
  reviewTime: {
    fontSize: '11px',
    color: COLORS.textSecondary,
  },
  reviewContent: {
    fontSize: '13px',
    color: COLORS.textSecondary,
    lineHeight: '1.5',
    margin: 0,
  },
  bottomBar: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    maxWidth: '480px',
    margin: '0 auto',
    backgroundColor: COLORS.card,
    padding: '12px 16px',
    display: 'flex',
    gap: '10px',
    borderTop: `1px solid ${COLORS.border}`,
    zIndex: 100,
  },
  favoriteBtn: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '8px 14px',
    borderRadius: '24px',
    backgroundColor: 'rgba(255,255,255,0.08)',
    color: COLORS.textSecondary,
    fontSize: '11px',
    cursor: 'pointer',
    border: `1px solid ${COLORS.border}`,
    gap: '2px',
  },
  favoriteBtnActive: {
    backgroundColor: `${COLORS.primary}20`,
    color: COLORS.primary,
    borderColor: `${COLORS.primary}40`,
  },
  favoriteIcon: {
    fontSize: '18px',
  },
  favoriteLabel: {
    fontSize: '10px',
  },
  chatBtn: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '10px 18px',
    borderRadius: '24px',
    background: `linear-gradient(135deg, ${COLORS.accent} 0%, #764ba2 100%)`,
    color: '#fff',
    fontSize: '12px',
    gap: '2px',
    cursor: 'pointer',
    boxShadow: `0 4px 12px ${COLORS.accent}40`,
    border: 'none',
  },
  chatIcon: {
    fontSize: '20px',
  },
  orderBtn: {
    flex: 1,
    background: `linear-gradient(135deg, ${COLORS.primary} 0%, ${COLORS.secondary} 100%)`,
    color: '#fff',
    padding: '14px',
    borderRadius: '24px',
    textAlign: 'center',
    fontSize: '16px',
    fontWeight: 'bold',
    cursor: 'pointer',
    boxShadow: `0 4px 15px ${COLORS.primary}40`,
    border: 'none',
  },
  orderBtnDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
}
