import { COLORS } from '@/constants'
import { Styles } from '@/utils/styles'

export const styles: Styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: COLORS.background,
    paddingBottom: '70px',
  },
  header: {
    background: `linear-gradient(135deg, ${COLORS.primary} 0%, #c44569 100%)`,
    paddingBottom: '20px',
  },
  profileSection: {
    display: 'flex',
    alignItems: 'center',
    padding: '24px 16px 16px',
    gap: '14px',
  },
  avatarArea: {
    position: 'relative',
    flexShrink: 0,
  },
  avatar: {
    width: '72px',
    height: '72px',
    borderRadius: '50%',
    backgroundColor: 'rgba(255,255,255,0.2)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '40px',
    border: '3px solid rgba(255,255,255,0.3)',
  },
  editBadge: {
    position: 'absolute',
    bottom: '2px',
    right: '2px',
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    backgroundColor: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    boxShadow: '0 2px 6px rgba(0,0,0,0.2)',
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontSize: '22px',
    fontWeight: 'bold',
    color: '#fff',
    margin: '0 0 6px 0',
  },
  riderBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  levelTag: {
    padding: '3px 10px',
    borderRadius: '12px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: '#fff',
  },
  phone: {
    fontSize: '13px',
    color: 'rgba(255,255,255,0.8)',
  },
  settingsIcon: {
    fontSize: '24px',
    cursor: 'pointer',
  },
  dataCards: {
    display: 'flex',
    backgroundColor: 'rgba(255,255,255,0.15)',
    margin: '0 12px',
    borderRadius: '16px',
    padding: '16px 8px',
    justifyContent: 'space-around',
  },
  dataCard: {
    textAlign: 'center',
    flex: 1,
  },
  dataValue: {
    display: 'block',
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#fff',
  },
  dataLabel: {
    fontSize: '11px',
    color: 'rgba(255,255,255,0.7)',
    marginTop: '2px',
    display: 'block',
  },
  badges: {
    backgroundColor: COLORS.card,
    margin: '12px 12px',
    borderRadius: '16px',
    padding: '16px',
    border: `1px solid ${COLORS.border}`,
  },
  badgeTitle: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: COLORS.text,
    margin: '0 0 12px 0',
  },
  badgeList: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
  },
  badgeItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: 'rgba(255,255,255,0.08)',
    padding: '6px 12px',
    borderRadius: '20px',
  },
  badgeIcon: {
    fontSize: '14px',
  },
  badgeText: {
    fontSize: '12px',
    color: COLORS.text,
  },
  menuSection: {
    backgroundColor: COLORS.card,
    margin: '0 12px',
    borderRadius: '16px',
    overflow: 'hidden',
    border: `1px solid ${COLORS.border}`,
  },
  menuItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 14px',
    borderBottom: `1px solid ${COLORS.border}`,
    cursor: 'pointer',
  },
  menuLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  menuIcon: {
    fontSize: '22px',
  },
  menuLabel: {
    fontSize: '15px',
    fontWeight: '500',
    color: COLORS.text,
    margin: 0,
  },
  menuSub: {
    fontSize: '12px',
    color: COLORS.textSecondary,
    margin: '2px 0 0 0',
  },
  menuArrow: {
    color: COLORS.textSecondary,
    fontSize: '16px',
  },
  logoutArea: {
    margin: '20px 12px 0',
  },
  logoutBtn: {
    width: '100%',
    padding: '15px',
    backgroundColor: 'transparent',
    border: `1px solid ${COLORS.border}`,
    borderRadius: '25px',
    fontSize: '15px',
    color: COLORS.textSecondary,
    cursor: 'pointer',
  },
  applyBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '14px',
    background: `linear-gradient(135deg, ${COLORS.primary}22 0%, ${COLORS.secondary}22 100%)`,
    border: `1px solid ${COLORS.primary}44`,
    borderRadius: '12px',
    marginTop: '12px',
    cursor: 'pointer',
  },
  applyIcon: {
    fontSize: '28px',
  },
  applyInfo: {
    flex: 1,
  },
  applyTitle: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: COLORS.text,
    margin: '0 0 2px 0',
  },
  applySub: {
    fontSize: '12px',
    color: COLORS.textSecondary,
    margin: 0,
  },
  applyBtn: {
    padding: '6px 16px',
    background: `linear-gradient(135deg, ${COLORS.primary} 0%, ${COLORS.secondary} 100%)`,
    borderRadius: '16px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: '#fff',
    cursor: 'pointer',
  },
}

